// Loacation actions
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';

export const SET_CURRENT_PLACES = 'SET_CURRENT_PLACES';

export const REQUEST_KINDS = 'REQUEST_KINDS';
export const RECEIVE_KINDS = 'RECEIVE_KINDS';
export const ERROR_REQUESTING_KINDS = 'ERROR_REQUESTING_KINDS';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

