// Loacation actions
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';

export const SET_CURRENT_PLACES = 'SET_CURRENT_PLACES';

export const REQUEST_KINDS = 'REQUEST_KINDS';
export const RECEIVE_KINDS = 'RECEIVE_KINDS';
export const ERROR_REQUESTING_KINDS = 'ERROR_REQUESTING_KINDS';

export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const ERROR_REQUESTING_CATEGORIES = 'ERROR_REQUESTING_CATEGORIES';

export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';
export const ERROR_REQUESTING_ITEMS = 'ERROR_REQUESTING_ITEMS';

export const REQUEST_SAVE_ITEM = 'REQUEST_SAVE_ITEM';
export const SAVE_ITEM_OK = 'SAVE_ITEM_OK';
export const SAVE_ITEM_KO = 'SAVE_ITEM_KO';




