// Loacation actions
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';

export const SET_CURRENT_PLACES = 'SET_CURRENT_PLACES';

export const REQUEST_KINDS = 'REQUEST_KINDS';
export const RECEIVE_KINDS = 'RECEIVE_KINDS';
export const ERROR_REQUESTING_KINDS = 'ERROR_REQUESTING_KINDS';

export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const ERROR_REQUESTING_CATEGORIES = 'ERROR_REQUESTING_CATEGORIES';


